
###
GET http://localhost:3000/appointments
Connection: keep-alive

###
QUERY http://localhost:3000/appointments
Content-Type: application/json
Connection: keep-alive

{
  "status": "completed"
}

###
GET http://localhost:3000/appointments/66
Connection: keep-alive

### 404
GET http://localhost:3000/appointments/999
Connection: keep-alive

###
POST http://localhost:3000/appointments
Content-Type: application/json
Connection: keep-alive

{
  "patientName": "Козлова Анна",
  "doctor": "Петрова А.С.",
  "date": "12-09",
  "time": "11:00",
  "reason": "Консультация"
}

###
PATCH http://localhost:3000/appointments/4
Content-Type: application/json
Connection: keep-alive

{
  "status": "scheduled"
}

### 400 
POST http://localhost:3000/appointments
Content-Type: application/json
Connection: keep-alive

{

}

###
PUT http://localhost:3000/appointments/4
Content-Type: application/json
Connection: keep-alive

{
  "patientName": "Иванов Иван Иванович",
  "doctor": "Петрова А.С.",
  "date": "12-09-2026",
  "time": "15:30",
  "reason": "Плановый осмотр",
  "status": "completed"
}

### 404
PUT http://localhost:3000/appointments/99
Content-Type: application/json
Connection: keep-alive

{
  "patientName": "Тест",
  "doctor": "Тест",
  "date": "10-09-2026",
  "time": "09:30"
}

###
DELETE http://localhost:3000/appointments/4

### 404
DELETE http://localhost:3000/appointments/999

### 404
GET http://localhost:3000/unknown-route
